# -*- coding: utf-8 -*-

"""
/***************************************************************************
 Flight Planner
                                 A QGIS plugin
 Flight Planner
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-11-05
        copyright            : (C) 2024 by Prof Cazaroli e Leandro França
        email                : contato@geoone.com.br
***************************************************************************/
"""

__author__ = 'Prof Cazaroli e Leandro França'
__date__ = '2024-11-05'
__copyright__ = '(C) 2024 by Prof Cazaroli e Leandro França'
__revision__ = '$Format:%H$'

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    from .PlanoVoo import PlanoVooPlugin
    from .PlanoVoo import PlanoVooPlugin
    return PlanoVooPlugin(iface)
